
apiVersion: apps/v1
kind: Deployment

metadata:
  name: ollama

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ollama

  template:
    metadata:
      labels:
        app: ollama

    spec:
      containers:
      - name: ollama
        image: ollama/ollama

        ports:
        - containerPort: 11434

        resources:
          requests:
            cpu: "100m"
            memory: "768Mi"
          limits:
            cpu: "250m"
            memory: "1200Mi"

        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                sleep 10
                ollama pull tinyllama

        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama

      volumes:
      - name: ollama-data
        emptyDir: {}
