apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama
        ports:
        - containerPort: 11434

        resources:
          limits:
            memory: "6Gi"
            cpu: "2"
          requests:
            memory: "3Gi"
            cpu: "1"

        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-data

      volumes:
      - name: ollama-data
        emptyDir: {}
